"""
embeddings.py — Offline TF-IDF embeddings wrapper for LangChain.

Used when HuggingFace Hub is not accessible (sandboxed environment).
In production, swap this with HuggingFaceEmbeddings("all-MiniLM-L6-v2")
for semantic similarity.

AI-assisted: Scaffold generated by Claude.
Prompt: "Write a LangChain-compatible Embeddings class that uses sklearn TF-IDF
so the system works fully offline without downloading any models."
"""

import hashlib
import pickle
import os
from typing import List

import numpy as np
from langchain_core.embeddings import Embeddings
from sklearn.feature_extraction.text import TfidfVectorizer  


VOCAB_CACHE = os.getenv("VOCAB_CACHE", "chroma_db/tfidf_vocab.pkl")
VECTOR_DIM = 512   


class LocalTFIDFEmbeddings(Embeddings):
    """
    Offline TF-IDF based embeddings.

    On first call to embed_documents(), a TfidfVectorizer is fit on the
    corpus and its vocabulary is cached to disk so query embeddings use
    the same space.
    """

    def __init__(self, vocab_cache: str = VOCAB_CACHE):
        self._cache_path = vocab_cache
        self._vectorizer: TfidfVectorizer | None = None

    def _ensure_vectorizer(self, texts: list[str] | None = None) -> TfidfVectorizer:
        if self._vectorizer is not None:
            return self._vectorizer

        if os.path.exists(self._cache_path):
            with open(self._cache_path, "rb") as f:
                self._vectorizer = pickle.load(f)
            return self._vectorizer

        if texts is None:
            raise RuntimeError(
                "TF-IDF vectorizer not yet fit. "
                "Call embed_documents() with the corpus first."
            )

        self._vectorizer = TfidfVectorizer(
            max_features=VECTOR_DIM,
            sublinear_tf=True,
            strip_accents="unicode",
            analyzer="word",
            token_pattern=r"(?u)\b\w+\b",
            ngram_range=(1, 2),
        )
        self._vectorizer.fit(texts)

        os.makedirs(os.path.dirname(self._cache_path), exist_ok=True)
        with open(self._cache_path, "wb") as f:
            pickle.dump(self._vectorizer, f)

        return self._vectorizer

    @staticmethod
    def _to_fixed_list(matrix, n: int = VECTOR_DIM) -> List[List[float]]:
        """Convert sparse matrix rows to fixed-length dense float lists."""
        dense = matrix.toarray()
        # Pad or truncate to n dims
        current_dim = dense.shape[1]
        if current_dim < n:
            dense = np.pad(dense, ((0, 0), (0, n - current_dim)))
        elif current_dim > n:
            dense = dense[:, :n]
        return dense.tolist()


    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """Fit (if needed) and transform a corpus of documents."""
        vec = self._ensure_vectorizer(texts)
        matrix = vec.transform(texts)
        return self._to_fixed_list(matrix)

    def embed_query(self, text: str) -> List[float]:
        """Transform a single query using the fitted vectorizer."""
        vec = self._ensure_vectorizer()
        matrix = vec.transform([text])
        return self._to_fixed_list(matrix)[0]